/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alexciocan' at '12/3/14 5:37 PM' with Gradle 2.2.1
 *
 * @author alexciocan, @date 12/3/14 5:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
